import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Request, RequestWithEmployee, TaskStatus, TaskType } from '@/types';

export function useRequests() {
  return useQuery({
    queryKey: ['requests'],
    queryFn: async (): Promise<RequestWithEmployee[]> => {
      const { data, error } = await supabase
        .from('requests')
        .select(`
          *,
          employee:employees(*)
        `)
        .order('date_requested', { ascending: false });

      if (error) throw error;
      
      return (data || []).map(item => ({
        ...item,
        task_type: item.task_type as TaskType,
        status: item.status as TaskStatus,
        employee: item.employee as RequestWithEmployee['employee']
      }));
    },
  });
}

export function useCreateRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: {
      employee_id: string;
      task_type: TaskType;
      task_description: string;
      target_completion_date: string;
      notes?: string;
      facebook_post_image_url?: string | null;
    }) => {
      const { data: result, error } = await supabase
        .from('requests')
        .insert({
          employee_id: data.employee_id,
          task_type: data.task_type,
          task_description: data.task_description,
          target_completion_date: data.target_completion_date,
          notes: data.notes || null,
          facebook_post_image_url: data.facebook_post_image_url ?? null,
          task_id: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['requests'] });
    },
  });
}

export function useUpdateRequestStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: TaskStatus }) => {
      const { error } = await supabase
        .from('requests')
        .update({ status })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['requests'] });
    },
  });
}

export function useDeleteRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('requests')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['requests'] });
    },
  });
}
