import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Request, RequestWithEmployee, TaskStatus, TaskType } from '@/types';

export function useRequests() {
  return useQuery({
    queryKey: ['requests'],
    queryFn: async (): Promise<RequestWithEmployee[]> => {
      const { data, error } = await supabase
        .from('requests')
        .select(`
          *,
          employee:employees(*)
        `)
        .order('date_requested', { ascending: false });

      if (error) throw error;
      
      return (data || []).map(item => ({
        ...item,
        task_type: item.task_type as TaskType,
        status: item.status as TaskStatus,
        employee: item.employee as RequestWithEmployee['employee']
      }));
    },
  });
}

export function useCreateRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: {
      employee_id: string;
      task_type: TaskType;
      task_description: string;
      target_completion_date: string;
      notes?: string;
      facebook_post_image_url?: string | null;
      dimension?: string | null;
    }) => {
      const { data: result, error } = await supabase
        .from('requests')
        .insert({
          employee_id: data.employee_id,
          task_type: data.task_type,
          task_description: data.task_description,
          target_completion_date: data.target_completion_date,
          notes: data.notes || null,
          facebook_post_image_url: data.facebook_post_image_url ?? null,
          dimension: data.dimension ?? null,
          task_id: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['requests'] });
      queryClient.invalidateQueries({ queryKey: ['user-requests'] });
    },
  });
}

export function useUpdateRequestStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: TaskStatus }) => {
      const { error } = await supabase
        .from('requests')
        .update({ status })
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['requests'] });
      queryClient.invalidateQueries({ queryKey: ['user-requests'] });
    },
  });
}

export function useDeleteRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('requests')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['requests'] });
      queryClient.invalidateQueries({ queryKey: ['user-requests'] });
    },
  });
}

export function useUserRequests() {
  return useQuery({
    queryKey: ['user-requests'],
    queryFn: async (): Promise<RequestWithEmployee[]> => {
      const { data: { user }, error: authError } = await supabase.auth.getUser();
      
      if (authError) {
        console.error('Auth error:', authError);
        throw new Error('User not authenticated');
      }
      
      if (!user?.email) {
        console.error('No user email found');
        throw new Error('User not authenticated');
      }

      console.log('Looking for employee with email:', user.email);

      // First, try to find employee by exact email match
      let { data: employee, error: employeeError } = await supabase
        .from('employees')
        .select('*')
        .eq('email', user.email)
        .single();

      // If not found, try case-insensitive search
      if (employeeError || !employee) {
        console.log('Trying case-insensitive email search...');
        const { data: employees } = await supabase
          .from('employees')
          .select('*')
          .ilike('email', user.email);
        
        if (employees && employees.length > 0) {
          employee = employees[0];
          employeeError = null;
        }
      }

      // If still not found, try to find by any employee that has this email in their data
      if (!employee) {
        console.log('Trying to find any employee with matching email...');
        const { data: allEmployees } = await supabase
          .from('employees')
          .select('*');
        
        // Filter manually for email match (case-insensitive)
        const matchingEmployee = allEmployees?.find(
          e => e.email?.toLowerCase() === user.email.toLowerCase()
        );
        
        if (matchingEmployee) {
          employee = matchingEmployee;
        }
      }

      if (employeeError) {
        console.error('Employee lookup error:', employeeError);
        throw employeeError;
      }

      if (!employee) {
        console.log('No employee found for email:', user.email);
        return [];
      }

      console.log('Found employee:', employee);
      console.log('Looking for requests with employee_id:', employee.id);

      const { data, error } = await supabase
        .from('requests')
        .select(`
          *,
          employee:employees(*)
        `)
        .eq('employee_id', employee.id)
        .order('date_requested', { ascending: false });

      if (error) {
        console.error('Requests lookup error:', error);
        throw error;
      }
      
      console.log('Found requests:', data?.length || 0);
      
      return (data || []).map(item => ({
        ...item,
        task_type: item.task_type as TaskType,
        status: item.status as TaskStatus,
        employee: item.employee as RequestWithEmployee['employee']
      }));
    },
  });
}
